name: flutter_map_rastercoords
description: "Flutter map utility library for non-geographic map projections using CRS Simple"
version: 0.0.2
homepage: https://github.com/jeremejazz/flutter_map_rastercoords
repository: https://github.com/jeremejazz/flutter_map_rastercoords
topics:
  - flutter-map
  - map
  - projection
funding:
  - https://ko-fi.com/jereme

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^8.1.1
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

